"""
Django settings for letsLearn project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import pymysql
import os
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================
# SECURITY
# ============================

SECRET_KEY = 'django-insecure-tqag4it82=m)s64ryggf6khm8##hh*gxs6c=l8dl(-p6acgboj'

DEBUG = True

ALLOWED_HOSTS = []


# ============================
# APPLICATIONS
# ============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'letsLearn',
    'authapp',

    # Cron jobs (for RSS email sending)
    'django_crontab',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'letsLearn.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'letsLearn.wsgi.application'


# ============================
# DATABASE
# ============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'burnlab',
        'USER': 'admin',
        'PASSWORD': 'password',
        'HOST': 'burnlab-db.cjikawewmt5w.us-east-2.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# ============================
# PASSWORD VALIDATION
# ============================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================
# INTERNATIONALIZATION
# ============================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================
# STATIC & MEDIA FILES
# ============================

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================
# DEFAULT PRIMARY KEY TYPE
# ============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================
# EMAIL CONFIGURATION (GMAIL)
# ============================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# REPLACE THESE TWO VALUES ↓↓↓
EMAIL_HOST_USER = "noreplyburnlabrss@gmail.com"              # your Gmail
EMAIL_HOST_PASSWORD = "jmwivvarhmbpdysi"       # Google App Password (NOT Gmail password)

EMAIL_FAIL_SILENTLY = False


# ============================
# CRON JOBS (RSS EMAIL SYSTEM)
# ============================

CRONJOBS = [
    # Runs the RSS update email every 30 minutes
    ("*/30 * * * *", "letsLearn.email_tasks.send_rss_updates"),
]
